name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.13.0]
    steps:
    - uses: actions/checkout@master
    - name: Node version
      run: node -v  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  
    - name: Create local changes
      run: |
        npm install
        npm run update-data
        npm run build
    - name: Commit files
      run: |
        git config --local user.email "ilyaflare@gmail.com"
        git config --local user.name "EVERYDAYHERO2000"
        git commit -m "Add changes" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.SECRET }}
        branch: 'gh-pages'
        force: true
