name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Run
      run: |
        npm install
        npm run update-data
      
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
