name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.13.0]

    runs-on: ubuntu-latest

    steps:
    - name: Node version
      run: node -v

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Node version
      run: node -v
      
    - uses: actions/checkout@v1
      
    - name: Run
      run: |
        npm install
        npm run update-data
      
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
